name: Build & Push Linode Webhook

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Install node and go
         run: apk add nodejs go
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: Build
         run: go build cmd/main.go
        

