name: Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        # run: apt update && apt -y install openssh-client
        run: apk add openssh-client
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitea-ssh.engen.priv.no >> ~/.ssh/known_hosts
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: ssh repo
        run: git config --global url.git@gitea-ssh.engen.priv.no:.insteadOf https://gitea.engen.priv.no/
      - name: Install ko
        run: go install github.com/google/ko@latest
      - name: Build
        env:
          KO_DOCKER_REPO: registry.engen.priv.no/unifi-network-operator-controller
          PATH: ~/go/bin:$PATH
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          ~/go/bin/ko publish ./cmd --tags "$TAG,latest"
