---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - unifi.engen.priv.no
  resources:
  - firewallgroups
  - firewallrules
  - firewallzones
  - networkconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - unifi.engen.priv.no
  resources:
  - firewallgroups/finalizers
  - firewallrules/finalizers
  - firewallzones/finalizers
  - networkconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - unifi.engen.priv.no
  resources:
  - firewallgroups/status
  - firewallrules/status
  - firewallzones/status
  - networkconfigurations/status
  verbs:
  - get
  - patch
  - update
