apiVersion: unifi.engen.priv.no/v1beta1
kind: FirewallRule
metadata:
  labels:
    app.kubernetes.io/name: unifi-network-operator
    app.kubernetes.io/managed-by: kustomize
  name: firewallrule-sample
spec:
