apiVersion: unifi.engen.priv.no/v1beta1
kind: FirewallGroup
metadata:
  labels:
    app.kubernetes.io/name: unifi-network-operator
    app.kubernetes.io/managed-by: kustomize
  name: firewallgroup-sample
spec:
  name: Test
  manualAddresses:
    - 192.168.1.153
    - 192.168.1.154
    - 192.168.1.155
    - 2a01::3
    - 2a01:0::5
    - 2a01:2a01::/32
  # TODO(user): Add fields here
