apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unifi-network-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifi-network-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "unifi-network-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "unifi-network-operator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "unifi-network-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        {{- if .Values.leaderElection.enabled }}
        - --leader-elect
        {{- end }}
        - --health-probe-bind-address=:8081
        env:
        - name: UNIFI_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "unifi-network-operator.secretName" . }}
              key: {{ .Values.unifi.existingSecretKeys.url }}
        - name: UNIFI_SITE
          valueFrom:
            secretKeyRef:
              name: {{ include "unifi-network-operator.secretName" . }}
              key: {{ .Values.unifi.existingSecretKeys.site }}
        - name: UNIFI_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "unifi-network-operator.secretName" . }}
              key: {{ .Values.unifi.existingSecretKeys.username }}
        - name: UNIFI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "unifi-network-operator.secretName" . }}
              key: {{ .Values.unifi.existingSecretKeys.password }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
