{{- if not .Values.unifi.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unifi-network-operator.fullname" . }}-unifi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifi-network-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.unifi.existingSecretKeys.url }}: {{ .Values.unifi.url | required "unifi.url is required when not using an existing secret" | quote }}
  {{ .Values.unifi.existingSecretKeys.site }}: {{ .Values.unifi.site | quote }}
  {{ .Values.unifi.existingSecretKeys.username }}: {{ .Values.unifi.username | quote }}
  {{ .Values.unifi.existingSecretKeys.password }}: {{ .Values.unifi.password | required "unifi.password is required when not using an existing secret" | quote }}
{{- end }}
