{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "unifi-network-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifi-network-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - interval: {{ .Values.metrics.serviceMonitor.interval }}
    path: /metrics
    port: https
    scheme: https
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      {{- include "unifi-network-operator.selectorLabels" . | nindent 6 }}
{{- end }}
