{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi-network-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifi-network-operator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: 8443
    protocol: TCP
  selector:
    {{- include "unifi-network-operator.selectorLabels" . | nindent 4 }}
{{- end }}
